apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-crash1
spec:
  selector:
    matchLabels:
      app: app-crash1
  replicas: 1
  template:
    metadata:
      labels:
        app: app-crash1
    spec:
      containers:
        - name: app-crash1
          image: centos:7
