apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: openshift/hello-openshift
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: backend-secret
          - configMapRef:
              name: backend-config
