apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-superproject
  namespace: my-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: superproject, operator: In, values: ["yes"]}