apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: after-inform-team
spec:
  job_template_name: send-slack-with-arg
  tower_auth_secret: tower-secret
  extra_vars:
    message: "APRES Deploiement application"